config/routes.rb
	require 'sidekiq/web'
	TriageRails::Application.routes.draw do
	 

	  # To be removed
		resource :account

		


		devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
	                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

	  # API Routes
	  namespace :api do
	    namespace :v1 do
	    	devise_for :users
	    	resource :account do
	    		member do
	    			get 'team'
	    			post 'avatar'
	    			post 'resend_verify_email'
	    			post 'welcome_complete'
	    			post 'reset_password'
	    		end
	    		resources :push_tokens do
	    			collection do
	    				post 'reset_count'
	    			end
	    		end
	    	end
	    	resources :apps do
	    		member do
	          get 'feed'
	          post 'ignore'
		    		post 'follow'
	        end
	        resources :providers do
		        collection do
		          get 'connected'
		        end
		    		
		    		member do
		    			post 'ignore'
		    			post 'follow'
		    			post 'email_connect_instructions'
		          get 'feed'
		    		end
						
						resources :accounts, controller: :provider_accounts
		    		resources :properties, controller: :provider_properties do
		  				member do
		  					post 'ignore'
		  					post 'follow'
		  				end
	  				end

		    	end
				end
	    	resources :feed do
	    		resources :share
	    		resources :messages
	    		
	    		resources :thumbsup do
	    			collection do
	    				post 'toggle'
	    			end
	    		end

	    		collection do 
	    			get 'mock'
	    			get 'view'
	    		end
	    	end
	      resources :team do
	        member do
	          get 'feed'
	        end
	      end
	    	
	    	resources :provider_accounts do
	  			resources :provider_properties do
	  				member do
	  					post 'ignore'
	  					post 'follow'
	  				end
	  			end
	  		end
	      resources :notifications, :only => :index do
	        member do 
	          post 'viewed'
	        end
	      end
	    end
	  end

	  resource :download
	  resources :share, :only => :show
	  resource  :team
	  
	  resources :apps do
	  	
	    resources :feed_items
	    resources :feed
	    resources :teammates
	    
	    resources :providers do
	    	member do 
	    		get 'webhook_settings'
	    		get 'settings'
	    	end

	      resources :accounts, controller: :provider_accounts do 
	        collection do 
	          get 'select'
	          post 'set_account'
	        end
	      end

	      resources :properties, controller: :provider_properties
	    end

	  end

	  # Webhooks
		scope module: 'services' do
			[:sentry, :new_relic, :kiln, :airbrake, :heroku, :hockey_app, :crashlytics, :beanstalk, :braintree, :bitbucket, :zapier, :trello].each do |resource|
	  		resources resource do
	  			collection do
	    			post ':company_id' => "#{resource}#webhook", as: 'webhook'
	          get 'validate' => "#{resource}#validate"
	    		end
	  		end
			end
	  	resources :github do
	  		collection do
	  			get 'org_list'
	  			post 'set_default_org'
	  			post ':company_id' => "github#webhook", as: 'webhook'
	  		end
	  	end
	    resources :stripe
	  	resources :google_analytics do
	  		collection do
	  			get 'account_list'
	  			post 'set_account'
	  		end
	  	end
	  end



	  get '/services/authenticate_for/:provider' => 'service#authenticate_for_oauth'
		get '/services/oauth_complete' => 'service#oauth_complete', as: 'oauth_complete'
		get '/services/oauth_failure/:error' => 'service#oauth_failure', as: 'oauth_failure'
		# Verification link
		get '/verify/:id/:token' => 'verify#show', as: 'verify_email'



		root :to => 'welcome#index'
		get '/faq' => 'welcome#faq', as: 'faq'
		get '/terms' => 'welcome#terms', as: 'terms'
		get '/press' => 'welcome#press', as: 'press'
		get '/about' => 'welcome#about', as: 'about'
	  get '/jobs' => 'welcome#jobs', as: 'jobs'
		post '/deliver_sms' => 'welcome#deliver_sms', as: 'deliver_sms'
		post '/capture_email' => 'welcome#capture_email', as: 'capture_email'
	  
	  resource :pilot do
	    member do
	      post 'complete'
	    end
	  end
		

		devise_for :admins, :controllers => { :registrations => "admin_registrations" }
		
		resource :admin do
			resources :users , :controller => 'admin/users'
			resources :companies , :controller => 'admin/companies'
			resources :feed_items , :controller => 'admin/feed_items'
			resources :messages , :controller => 'admin/messages'
      resources :providers, :controller => 'admin/providers'
      resources :provider_sections, :controller => 'admin/provider_sections'
			mount Sidekiq::Web => '/sidekiq'
		end
		

		#mount Dashing::Engine, at: Dashing.config.engine_path
		
		#mount Resque::Server, :at => "/resque"
		
	end

app/views/shared/_download_overlay.html.erb
	<div id="downloading">
		<div class="download-region">
  	 	<h1 style="color:#ffffff;">Triage Is Coming Soon</h1>
  	 	<%= simple_form_for :email_capture, :url => capture_email_path, :method => :post, :remote => :true, :html => {:id => 'sms_delivery_form', :class => 'form-inline hidden-md hidden-sm'} do |f| %>
			<div class="col-lg-12 col-sm-12">
				<div class="row">
					<br /><br />
		  		<%= f.input_field :email, :id => "phone_number", :placeholder => 'me@email.com', :autocomplete => "off"%>
		  		<%= f.button :submit, "NOTIFY ME", :class => "btn-submit" %>
		  		<%= image_tag("input-line.png", :id => "input-line") %>
		  		<div class="row center-block">
						<p id="response" class="center-block" style="visibility:hidden;text-align:center;">abc</p>
					</div>
		  	</div>
		  	<!-- <div class="row">
		  		<p>or</p>
		  	</div>
		  	<div class="row">
		  		<br /><br />
		  		<%= link_to image_tag("available.png"), "https://itunes.apple.com/us/app/triage-everything-thats-happening/id744662903?ls=1&mt=8" %>
		  	</div>
	 		</div> -->
	</div> 
<% end %>
<div class="col-lg-12">
	
</div>
  	 </div>
	</div>

app/views/shared/_overlay.html.erb
<% content_for :overlay do %>
	<div id="downloading">
		<div class="download-region">
  	 	<h1>Download Triage for iOS</h1>
  	 	<%= simple_form_for :sms_delivery, :url => deliver_sms_path, :method => :post, :remote => :true, :html => {:id => 'sms_delivery_form', :class => 'form-inline hidden-md hidden-sm'} do |f| %>
			<div class="col-lg-12 col-sm-12">
				<div class="row">
					<br /><br />
		  		<%= f.input_field :phone_number, :id => "phone_number", :placeholder => '(555) 555-5555', :autocomplete => "off"%>
		  		<%= f.button :submit, "TEXT ME A LINK", :class => "btn-submit" %>
		  		<%= image_tag("input-line.png", :id => "input-line") %>
		  		<div class="row center-block">
						<p id="response" class="center-block" style="visibility:hidden;text-align:center;">abc</p>
					</div>
		  	</div>
		  	<div class="row">
		  		<p>or</p>
		  	</div>
		  	<div class="row">
		  		<br /><br />
		  		<%= link_to image_tag("available.png"), "https://itunes.apple.com/us/app/triage-everything-thats-happening/id744662903?ls=1&mt=8" %>
		  	</div>
	 		</div>
	</div> 
<% end %>
		<div class="col-lg-12">
			
		</div>
  	 </div>
	</div>
<% end %>

app/views/shared/_twitter_tags.html.erb
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@triagedco">
<meta name="twitter:title" content="Triage - Everything that's happening at work">
<meta name="twitter:description" content="Triage monitors the services you already use at work and syncs everything important into one mobile feed. With Triage, a quick glance keeps you up to date on key business metrics and activity.">
<meta name="twitter:image:src" content="http:<%= image_url 'iphone.png' %>">
<meta name="twitter:app:id:iphone" content="744662903">
<meta name="twitter:app:name:iphone" content="Triage - Everything that's happening at work">