config/routes.rb
	require 'sidekiq/web'
	TriageRails::Application.routes.draw do
	 

	  # To be removed
		resource :account

		


		devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
	                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

	  # API Routes
	  namespace :api do
	    namespace :v1 do
	    	devise_for :users
	    	resource :account do
	    		member do
	    			get 'team'
	    			post 'avatar'
	    			post 'resend_verify_email'
	    			post 'welcome_complete'
	    			post 'reset_password'
	    		end
	    		resources :push_tokens do
	    			collection do
	    				post 'reset_count'
	    			end
	    		end
	    	end
	    	resources :apps do
	    		member do
	          get 'feed'
	          post 'ignore'
		    		post 'follow'
	        end
	        resources :providers do
		        collection do
		          get 'connected'
		        end
		    		
		    		member do
		    			post 'ignore'
		    			post 'follow'
		    			post 'email_connect_instructions'
		          get 'feed'
		    		end
						
						resources :accounts, controller: :provider_accounts
		    		resources :properties, controller: :provider_properties do
		  				member do
		  					post 'ignore'
		  					post 'follow'
		  				end
	  				end

		    	end
				end
	    	resources :feed do
	    		resources :share
	    		resources :messages
	    		
	    		resources :thumbsup do
	    			collection do
	    				post 'toggle'
	    			end
	    		end

	    		collection do 
	    			get 'mock'
	    			get 'view'
	    		end
	    	end
	      resources :team do
	        member do
	          get 'feed'
	        end
	      end
	    	
	    	resources :provider_accounts do
	  			resources :provider_properties do
	  				member do
	  					post 'ignore'
	  					post 'follow'
	  				end
	  			end
	  		end
	      resources :notifications, :only => :index do
	        member do 
	          post 'viewed'
	        end
	      end
	    end
	  end

	  resource :download
	  resources :share, :only => :show
	  resource  :team
	  
	  resources :apps do
	  	
	    resources :feed_items
	    resources :feed
	    resources :teammates
	    
	    resources :providers do
	    	member do 
	    		get 'webhook_settings'
	    		get 'settings'
	    	end

	      resources :accounts, controller: :provider_accounts do 
	        collection do 
	          get 'select'
	          post 'set_account'
	        end
	      end

	      resources :properties, controller: :provider_properties
	    end

	  end

	  # Webhooks
		scope module: 'services' do
			[:sentry, :new_relic, :kiln, :airbrake, :heroku, :hockey_app, :crashlytics, :beanstalk, :braintree, :bitbucket, :zapier, :trello].each do |resource|
	  		resources resource do
	  			collection do
	    			post ':company_id' => "#{resource}#webhook", as: 'webhook'
	          get 'validate' => "#{resource}#validate"
	    		end
	  		end
			end
	  	resources :github do
	  		collection do
	  			get 'org_list'
	  			post 'set_default_org'
	  			post ':company_id' => "github#webhook", as: 'webhook'
	  		end
	  	end
	    resources :stripe
	  	resources :google_analytics do
	  		collection do
	  			get 'account_list'
	  			post 'set_account'
	  		end
	  	end
	  end



	  get '/services/authenticate_for/:provider' => 'service#authenticate_for_oauth'
		get '/services/oauth_complete' => 'service#oauth_complete', as: 'oauth_complete'
		get '/services/oauth_failure/:error' => 'service#oauth_failure', as: 'oauth_failure'
		# Verification link
		get '/verify/:id/:token' => 'verify#show', as: 'verify_email'



		root :to => 'welcome#index'
		get '/faq' => 'welcome#faq', as: 'faq'
		get '/terms' => 'welcome#terms', as: 'terms'
		get '/press' => 'welcome#press', as: 'press'
		get '/about' => 'welcome#about', as: 'about'
	  get '/jobs' => 'welcome#jobs', as: 'jobs'
		post '/deliver_sms' => 'welcome#deliver_sms', as: 'deliver_sms'
		post '/capture_email' => 'welcome#capture_email', as: 'capture_email'
	  
	  resource :pilot do
	    member do
	      post 'complete'
	    end
	  end
		

		devise_for :admins, :controllers => { :registrations => "admin_registrations" }
		
		resource :admin do
			resources :users , :controller => 'admin/users'
			resources :companies , :controller => 'admin/companies'
			resources :feed_items , :controller => 'admin/feed_items'
			resources :messages , :controller => 'admin/messages'
      resources :providers, :controller => 'admin/providers'
      resources :provider_sections, :controller => 'admin/provider_sections'
			mount Sidekiq::Web => '/sidekiq'
		end
		

		#mount Dashing::Engine, at: Dashing.config.engine_path
		
		#mount Resque::Server, :at => "/resque"
		
	end

app/models/pilot.rb
class Pilot
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :company, type: String
  field :teamsize, type: Integer
  field :team, type: String
  field :saas_other, type: String
  field :team_other, type: String
  field :saas, type: Array
  field :os, type: String
end

app/controllers/admin/pilots_controller.rb
class Admin::PilotsController < ApplicationController
	before_action :authenticate_admin!
	

	def index
		@pilots = Pilot.all
	end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController

	def show
	end

	def complete
		Rails.logger.info pilot_params
		Rails.logger.info params[:pilot]
		Pilot.create(pilot_params)
		Common::CaptureEmail.subscribe(pilot_params[:email])
	end

	def pilot_params
		params.require(:pilot).permit!
	end

end

app/helpers/admin/pilots_helper.rb
module Admin::PilotsHelper
end

app/helpers/pilot_helper.rb
module PilotHelper
end

app/views/pilots/complete.html.erb
<div class="container fullheight">
	<div class="col-lg-12 col-sm-12">
		<div class="row center padding-top-sm">
			<%= image_tag "triage-logo-sm.png" %>
		</div>

		<div class="row center">
			<div class="col-lg-8 col-lg-offset-2 padding-top-xsm">
				<h2>Thanks so much!</h2>
				<p class="altbody">We'll email you if you are chosen for the pilot program.</p>
				<br>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3 padding-top-sm center">
				<h3>Want to increase your odd's of being chosen? <br> Let your friends know about Triage.</h3>
				<!-- <p>Companies with multiple teammates who fill out the questionnnaire will increase your chances to be chosen for the pilot.</p> -->
			</div>
		</div>
		<div class="row padding-top-sm center">		
			<div class="col-lg-6 col-lg-offset-3 center">
				<a class="btn-custom-3" href="http://twitter.com/home?status=Check%20out%20%40triagedco%2C%20the%20best%20way%20to%20stay%20on%20top%20of%20work.%20I%20just%20signed%20up%20for%20the%20pilot.%20goo.gl%2FW0roSN">
					<span><%= render "pilots/svg/twitter" %>
						Tweet
					</span>
				</a>
			</div>
		</div>
	</div>

	<div class="center navbar-fixed-bottom">
		<div class="row padding-top-sm padding-bottom-sm" id="complete-bottom">
			<div class="col-lg-6 col-lg-offset-3 center">
				<%= link_to 'Return To Homepage', root_path, :class => "btn btn-lg btn-custom", :type => "button" %>
			</div>
		</div>
	</div>

</div>

app/views/pilots/show.html.erb
<!-- First Screen -->

<div class="container fullheight">
	<div class="row center padding-top-sm">
		<%= image_tag "triage-logo-sm.png" %>
	</div>

	<%= simple_form_for :pilot, :url => complete_pilot_path, :method => :post, :html => {:id => 'pilotForm' } do |f| %>
	
	<!-- Carousel -->	
	<div class="container fill">
		<div id="myCarousel" class="carousel slide" data-interval="false" data-wrap="false">
    		<div class="carousel-inner">

				<!-- First Slide -->
				<div class="active item">
					<div class="row center">
						<div class="col-lg-8 col-lg-offset-2 padding-top-xsm">
							<h2>Attn: All Modern Teams</h2>
							<p class="altbody padding-top-xsm">We are selecting a few incredible teams to partner with us when we launch. To ensure your team is the right fit we've put together a couple of questions. <br /> It won't take more than two minutes.</p>
						</div>
					</div>
					<div class="row padding-top-sm">
						<div class="col-lg-4 col-lg-offset-4 col-sm-4 col-sm-offset-4">
							<form role="form">
							  <div class="form-group">
							    <input type="text" id="username" name="pilot[name]" class="form-control form-control-custom" placeholder="Your Full Name" type="text" required>
							  </div>
							  <div class="form-group">
							    <input type="email" name="pilot[email]" type="email" class="form-control form-control-custom" placeholder="Work Email" required>
							  </div>
							  <div class="form-group">
							    <input type="text" name="pilot[company]" class="form-control form-control-custom" placeholder="Company Name" type="text" required>
							  </div>
							</form>
						</div>
					</div>
				</div>
				<!-- End First Slide -->

				<!-- Second Slide -->
				<div class="item">
					<div class="row center">

						<div class="col-lg-8 col-lg-offset-2 padding-top-sm">
							<h2>How large is your company?</h2>
						</div>
					</div>
					
					<div class="row label-padding center">	
						<div class="checkbox-fixed">
							<label>
								<%= render "pilots/svg/teamsm" %>
								<input type="radio" name="pilot[teamsize]" value="1">
								<span>1-20</span>
							</label>

							<label>
								<%= render "pilots/svg/teamm" %>
								<input type="radio" name="pilot[teamsize]" value="21">
								<span>21-50</span>
							</label>

							<label>
								<%= render "pilots/svg/teamlg" %>
								<input type="radio" name="pilot[teamsize]" value="51">
								<span>51-100</span>
							</label>

							<label>
								<%= render "pilots/svg/teamxlg" %>
								<input type="radio" name="pilot[teamsize]" value="100">
								<span>100+</span>
							</label>
						</div>
					</div>

				</div>
				<!-- End Second Slide -->

				<!-- Third Slide -->
				<div class="item">
					<div class="row center">
						<div class="col-lg-8 col-lg-offset-2 padding-top-sm">
							<h2>What team do you work on?</h2>
						</div>
					</div>
					
					<div class="row label-padding center">
						<div class="col-lg-12 col-lg-offset-0 col-sm-10 col-sm-offset-1">	
							<div class="checkbox-fixed">
								<label>
									<%= render "pilots/svg/design" %>
									<input type="radio" name="pilot[team]" value="design">
									<span>Design</span>
								</label>

								<label>
									<%= render "pilots/svg/engineering" %>
									<input type="radio" name="pilot[team]" value="engineering">
									<span>Engineering</span>
								</label>

								<label>
									<%= render "pilots/svg/operations" %>
									<input type="radio" name="pilot[team]" value="operations">
									<span>Operations</span>
								</label>

								<label>
									<%= render "pilots/svg/sales" %>
									<input type="radio" name="pilot[team]" value="sales">
									<span>Sales</span>
								</label>

								<label>
									<%= render "pilots/svg/support" %>
									<input type="radio" name="pilot[team]" value="support">
									<span>Support</span>
								</label>
							</div>
						</div>
					</div>

					<div class="col-lg-12 padding-top-sm center">	
						<div class="checkbox-fixed">
							<label id="other-team">
								<input type="checkbox" name="pilot[team]" value="">
								<span>Other</span>
							</label>
							
							<div class="col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 padding-top-sm center" id="other-team-input" style="display:none;">
								<div class="form-group">
							    <input type="text" name="pilot[team_other]" class="form-control form-control-custom" placeholder="Other Team">
							  </div>
							</div>
						</div>
					</div>
				</div>
				<!-- End Second Slide -->


				<!-- Fourth Slide -->
				<div class="item">
					<div class="row center">
						<div class="col-lg-10 col-lg-offset-1 padding-top-sm">
							<h2>What SaaS services do you use at work?</h2>
						</div>
					</div>

					<div class="row label-padding center">
						<div class="col-lg-12 col-sm-4">	
							<div class="checkbox-fitted">
								<label>
									<input type="checkbox" name="pilot[saas][]" value="airbrake">
									<span><%= image_tag "icons/airbrake-icon-sm.png", :width => "23" %>Airbrake</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="aws">
									<span><%= image_tag "icons/amazon-icon-sm.png", :width => "23" %>Amazon Web Services</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="appfigures">
									<span><%= image_tag "icons/appfigures-icon-sm.png", :width => "23" %>Appfigures</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="asana">
									<span><%= image_tag "icons/asana-icon-sm.png", :width => "23" %>Asana</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="beanstalk">
									<span><%= image_tag "icons/beanstalk-icon-sm.png", :width => "23" %>Beanstalk</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="bitbucket">
									<span><%= image_tag "icons/bitbucket-icon-sm.png", :width => "23" %>Bitbucket</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="box">
									<span><%= image_tag "icons/box-icon-sm.png", :width => "23" %>Box</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="crashlytics">
									<span><%= image_tag "icons/crashlytics-icon-sm.png", :width => "23" %>Crashlytics</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="dropbox">
									<span><%= image_tag "icons/dropbox-icon-sm.png", :width => "23" %>Dropbox</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="evernote">
									<span><%= image_tag "icons/evernote-icon-sm.png", :width => "23" %>Evernote</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="googleanalytics">
									<span><%= image_tag "icons/ga-icon-sm.png", :width => "23" %>Google Analytics</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="github">
									<span><%= image_tag "icons/github-icon-sm.png", :width => "23" %>Github</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="googledrive">
									<span><%= image_tag "icons/googledrive-icon-sm.png", :width => "23" %>Google Drive</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="heroku">
									<span><%= image_tag "icons/heroku-icon-sm.png", :width => "23" %>Heroku</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="HockeyApp">
									<span><%= image_tag "icons/hockeyapp-icon-sm.png", :width => "23" %>HockeyApp</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Kiln">
									<span><%= image_tag "icons/kiln-icon-sm.png", :width => "23" %>Kiln</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Layervault">
									<span><%= image_tag "icons/layervault-icon-sm.png", :width => "23" %>Layervault</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="NewRelic">
									<span><%= image_tag "icons/newrelic-icon-sm.png", :width => "23" %>New Relic</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Sentry">
									<span><%= image_tag "icons/sentry-icon-sm.png", :width => "23" %>Sentry</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Stripe">
									<span><%= image_tag "icons/stripe-icon-sm.png", :width => "23" %>Stripe</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="TravisCI">
									<span><%= image_tag "icons/travisci-icon-sm.png", :width => "23" %>Travis CI</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Trello">
									<span><%= image_tag "icons/trello-icon-sm.png", :width => "23" %>Trello</span>
								</label>
								<label>
									<input type="checkbox" name="pilot[saas][]" value="Zendesk">
									<span><%= image_tag "icons/zendesk-icon-sm.png", :width => "23" %>Zendesk</span>
								</label>
							</div>
						</div>
					</div>

					<div class="col-lg-12 padding-top-sm center">	
						<div class="checkbox-fixed">
							<label id="other-services">
								<input type="checkbox" name="saas" value="">
								<span>Other</span>
							</label>
							
							<div class="col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 padding-top-sm center" id="other-services-input" style="display:none;">
								<div class="form-group">
							    <input type="text" name="pilot[saas_other]" class="form-control form-control-custom" placeholder="Other SaaS Services">
							  </div>
							</div>
						</div>
					</div>
				</div>
				<!-- End Fourth Slide -->

				<!-- Fifth Slide -->
				<div class="item">
					<div class="row center">
						<div class="col-lg-10 col-lg-offset-1 padding-top-sm">
							<h2>Last question. What phone OS do you use?</h2>
						</div>
					</div>
					
					<div class="row label-padding center">	
						<div class="checkbox-fixed">
							<label>
								<%= render "pilots/svg/apple" %>
								<input type="radio" name="pilot[os]" value="ios">
								<span>iOS</span>
							</label>

							<label>
								<%= render "pilots/svg/android" %>
								<input type="radio" name="pilot[os]" value="android">
								<span>Android</span>
							</label>

							<label>
								<%= render "pilots/svg/windows" %>
								<input type="radio" name="pilot[os]" value="windows">
								<span>Windows</span>
							</label>

							<label>
								<%= render "pilots/svg/blackberry" %>
								<input type="radio" name="pilot[os]" value="blackberry">
								<span>Blackberry</span>
							</label>
						</div>
					</div>
				</div>
				<!-- End Fifth Slide -->
			</div>
		</div>
	</div>

	<% end %>

	<!-- Pagination -->
	<div class="center navbar-fixed-bottom">
		<div class="row">
			<div class="col-lg-4 col-lg-offset-4 center">
				<button class="btn-custom-2" type="button" id="slideButton" href="#myCarousel" data-slide="next">
					Next
				</button>
			</div>
		</div>
		<div class="row padding-top-sm">
			<ul class="pagination-custom">
			  <li class="active"><a href="#1">1</a></li>
			  <hr class="pagination-line">
			  <li><a href="#2">2</a></li>
			  <hr class="pagination-line">
			  <li><a href="#3">3</a></li>
			  <hr class="pagination-line">
			  <li><a href="#4">4</a></li>
			  <hr class="pagination-line">
			  <li><a href="#5">5</a></li>
			</ul>
		</div>
	</div>

</div>