config/routes.rb
	require 'sidekiq/web'
	TriageRails::Application.routes.draw do
	 

	  # To be removed
		resource :account

		


		devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
	                   controllers: {omniauth_callbacks: "omniauth_callbacks"}

	  # API Routes
	  namespace :api do
	    namespace :v1 do
	    	devise_for :users
	    	resource :account do
	    		member do
	    			get 'team'
	    			post 'avatar'
	    			post 'resend_verify_email'
	    			post 'welcome_complete'
	    			post 'reset_password'
	    		end
	    		resources :push_tokens do
	    			collection do
	    				post 'reset_count'
	    			end
	    		end
	    	end
	    	resources :apps do
	    		member do
	          get 'feed'
	          post 'ignore'
		    		post 'follow'
	        end
	        resources :providers do
		        collection do
		          get 'connected'
		        end
		    		
		    		member do
		    			post 'ignore'
		    			post 'follow'
		    			post 'email_connect_instructions'
		          get 'feed'
		    		end
						
						resources :accounts, controller: :provider_accounts
		    		resources :properties, controller: :provider_properties do
		  				member do
		  					post 'ignore'
		  					post 'follow'
		  				end
	  				end

		    	end
				end
	    	resources :feed do
	    		resources :share
	    		resources :messages
	    		
	    		resources :thumbsup do
	    			collection do
	    				post 'toggle'
	    			end
	    		end

	    		collection do 
	    			get 'mock'
	    			get 'view'
	    		end
	    	end
	      resources :team do
	        member do
	          get 'feed'
	        end
	      end
	    	
	    	resources :provider_accounts do
	  			resources :provider_properties do
	  				member do
	  					post 'ignore'
	  					post 'follow'
	  				end
	  			end
	  		end
	      resources :notifications, :only => :index do
	        member do 
	          post 'viewed'
	        end
	      end
	    end
	  end

	  resource :download
	  resources :share, :only => :show
	  resource  :team
	  
	  resources :apps do
	  	
	    resources :feed_items
	    resources :feed
	    resources :teammates
	    
	    resources :providers do
	    	member do 
	    		get 'webhook_settings'
	    		get 'settings'
	    	end

	      resources :accounts, controller: :provider_accounts do 
	        collection do 
	          get 'select'
	          post 'set_account'
	        end
	      end

	      resources :properties, controller: :provider_properties
	    end

	  end

	  # Webhooks
		scope module: 'services' do
			[:sentry, :new_relic, :kiln, :airbrake, :heroku, :hockey_app, :crashlytics, :beanstalk, :braintree, :bitbucket, :zapier, :trello].each do |resource|
	  		resources resource do
	  			collection do
	    			post ':company_id' => "#{resource}#webhook", as: 'webhook'
	          get 'validate' => "#{resource}#validate"
	    		end
	  		end
			end
	  	resources :github do
	  		collection do
	  			get 'org_list'
	  			post 'set_default_org'
	  			post ':company_id' => "github#webhook", as: 'webhook'
	  		end
	  	end
	    resources :stripe
	  	resources :google_analytics do
	  		collection do
	  			get 'account_list'
	  			post 'set_account'
	  		end
	  	end
	  end



	  get '/services/authenticate_for/:provider' => 'service#authenticate_for_oauth'
		get '/services/oauth_complete' => 'service#oauth_complete', as: 'oauth_complete'
		get '/services/oauth_failure/:error' => 'service#oauth_failure', as: 'oauth_failure'
		# Verification link
		get '/verify/:id/:token' => 'verify#show', as: 'verify_email'



		root :to => 'welcome#index'
		get '/faq' => 'welcome#faq', as: 'faq'
		get '/terms' => 'welcome#terms', as: 'terms'
		get '/press' => 'welcome#press', as: 'press'
		get '/about' => 'welcome#about', as: 'about'
	  get '/jobs' => 'welcome#jobs', as: 'jobs'
		post '/deliver_sms' => 'welcome#deliver_sms', as: 'deliver_sms'
		post '/capture_email' => 'welcome#capture_email', as: 'capture_email'
	  
	  resource :pilot do
	    member do
	      post 'complete'
	    end
	  end
		

		devise_for :admins, :controllers => { :registrations => "admin_registrations" }
		
		resource :admin do
			resources :users , :controller => 'admin/users'
			resources :companies , :controller => 'admin/companies'
			resources :feed_items , :controller => 'admin/feed_items'
			resources :messages , :controller => 'admin/messages'
      resources :providers, :controller => 'admin/providers'
      resources :provider_sections, :controller => 'admin/provider_sections'
			mount Sidekiq::Web => '/sidekiq'
		end
		

		#mount Dashing::Engine, at: Dashing.config.engine_path
		
		#mount Resque::Server, :at => "/resque"
		
	end

app/views/apps/_form.html.erb
<%= simple_form_for(@app, :url => apps_path) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
	<%= f.input :name %>

	<!-- rails helper - needs to be connected -->
	<% if false %>
	<%= f.input :app_type, :as => :string %>
	<% end %>
	<!-- end -->
	
	<form role="form">
	  <div class="form-group">
	    <label for="exampleInputEmail1">Application Type</label>
			<select class="form-control">
				<option>Web Application</option>
				<option>Mobile Application</option>
				<option>Service Application</option>
			</select>
		</div>
	</form>
</div>
<div class="form-actions">
	<%= f.submit "Create App" %>
	<button><%= link_to 'Cancel', apps_path %></button>
</div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app_application</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_application %> |
<%= link_to 'Back', app_applications_path %>

app/views/apps/index.html.erb
<div class="container">
   <header>
      <nav class="navbar padding-top-sm">
         <div class="navbar-header">
            <%= link_to (image_tag 'triage-logo-sm.png'), apps_path %>
            <%= link_to 'Triage', apps_path, :id => "logotype" %>
         </div>
         <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Applications', apps_path %></li>
            <li><%= link_to 'Team', team_path %></li>
         </ul>
         <div class="nav navbar-nav navbar-right">
            <%= link_to 'Profile', account_path %>
         </div>
      </nav>
   </header>
   <main>
   <div class="content">
      <div class="col-lg-6 col-lg-offset-3">
         <div class="section-header">
            <h1>[Company]'s Apps</h1>
            <p>
            Follow one of your company’s apps or create your own.</br>
            Click on the app’s name to configure settings.
            </p>
         </div>
         <div class="section-content">
            <div class="section-headline">
               <% @apps.each do |app| %>
            </div>
            <div class="section">
               <h3><%= app.app_type %></h3>        
               <div class="app">
                  <div class="app-logo">
                  </div>
                  <h4><%= app.name %></h4>
                  <div class="settings-icon">
                     <%= link_to (image_tag 'application/settings-2.svg'), app_path(app) %>
                  </div>
               </div>
               <div class="app">
                  <div class="app-logo">
                  </div>
                  <h4><%= app.name %></h4>
                  <div class="settings-icon">
                     <%= link_to (image_tag 'application/settings-2.svg'), app_path(app) %>
                  </div>
               </div>
            </div>
            <% end %>
         </div>
         <div class="add-app">
            <h3>Add Application</h3>
            <p>Connect all your apps to become a work jedi.</p>
            <button class="btn add-btn"><%= link_to 'New Application', new_app_path %></button>
         </div>
      </div>
   </div>
   </main>
   <footer>
   </footer>

         <% @apps.each do |app| %>
            <td><%= app.name %> </td>
            <td><%= app.app_type %> </td>
            <td><%= link_to 'Show', app_path(app) %></td>
            <td><%= link_to 'Edit', edit_app_path(app) %></td>
            <td><%= link_to 'Destroy', app_path(app), method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <% end %>

app/views/apps/new.html.erb
<div class="container">
	<header>
		<nav class="navbar padding-top-sm">
			<div class="navbar-header">
				<%= link_to (image_tag 'triage-logo-sm.png'), apps_path %>
				<%= link_to 'Triage', apps_path, :id => "logotype" %>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><%= link_to 'Applications', apps_path %></li>
				<li><%= link_to 'Team', team_path %></li>
			</ul>
			<div class="nav navbar-nav navbar-right">
				<%= link_to 'Profile', account_path %>
			</div>
		</nav>
	</header>
  <main>
  <div class="content">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="section-header">
        <h4>Create An Application</h4>
        <p>
        Track the activity of your application and do more from your phone.
        </p>
      </div>
      <div class="section-content">
        <div class="section">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
  </main>
</div>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<%= @app.name %> <br />

<% @providers.each do |provider| %>
	<%= image_tag provider.large_icon.url %> <%= link_to provider.name, app_provider_path(@app, provider) %> - <%= @app.connected_to_provider? provider %>
	<hr />
<% end %>


<td><%= link_to 'Edit', edit_app_path(@app) %></td>
<td><%= link_to 'Destroy', app_path(@app), method: :delete, data: { confirm: 'Are you sure?' } %></td>


<%= link_to 'Back', app_path %>